### ISSUE TITLE
Test failure: Util › Generate content id

### ISSUE THREAD

**Issue by dboreham** [cerc-io/laconic-sdk#7] opened 2022-11-04 15:21 UTC
```
  ● Util › Generate content id.

    expect(received).toBe(expected) // Object.is equality

    Expected: "bafyreic3p6otn5mf236vkw4p2lxzeij5gmoi3rmcujc3puolhjdtsfwipi"
    Received: "bafyreif7z4lbftuxkj7nu4bl7xihitqvhus3wmoqdkjo7lwv24j6fkfskm"

      42 |   test('Generate content id.', async () => {
      43 |     const cid = await Util.getContentId(watcher.record);
    > 44 |     expect(cid).toBe(watcherId)
         |                 ^
      45 |   });
      46 | }
      47 |

      at src/util.test.ts:44:17
      at fulfilled (src/util.test.ts:5:58)
```

**Comment by zramsay** [comment] 2023-01-11 23:23
fails for me too (the only one)

**Comment by i-norden** [comment] 2023-01-13 19:11
This is the issue I assume to be due to swtichign from sha2-512 to sha2-256 in https://github.com/vulcanize/chiba-clonk/pull/45/files

But, that was a change from sha2-512 to sha2-256 in the pending PR. The old go-ipld-cbor codec we replaced in that PR was alreasy using sha2-256.

Also, if it were due to a change like this I would expect all tests that are testing contentIDs to fail.

I think what happened instead is that the content itself was changed when changing the attribute types in https://github.com/cerc-io/laconicd/pull/40 (watcher registration object was changed) and the corresponding changes were not made here.

Just thoughts right now I still need to test things.

**Comment by i-norden** [comment] 2023-01-18 16:42
Due to the amount of overlap between the two CIDs we can conclude that it is not due to the wrong CID version, multihash prefix, or multicontent prefix being used. It either must be due to differences in the contentg itself, or the IPLD codecs are encoding/decoding incorrectly.

**Comment by i-norden** [comment] 2023-01-19 15:57
So I’m thinking the problem is:
In the cbor.FromJSON function inside of CIDFromJSONBytes, the JSON is [decoded](https://github.com/ipfs/go-ipld-cbor/blob/master/node.go#L461) and converted to a [CBOR object](https://github.com/ipfs/go-ipld-cbor/blob/master/node.go#L466) before it is [marshalled into DAG CBOR](https://github.com/ipfs/go-ipld-cbor/blob/master/node.go#L117). It is then these marshalled DAG CBOR bytes that are hashed into a CID.
CIDFromJSONBytesUsingIpldPrime does not appear to be doing this, it appears to be computing the CID off the raw input JSON bytes without converting and encoding it as DAG CBOR first.

**Comment by i-norden** [comment] 2023-01-19 16:06
I think we need to reimplement a helper function like  `cbor.FromJSON`

But instead of using the [go-ipld-cbor marshaller](https://github.com/ipfs/go-ipld-cbor/blob/master/node.go#L117)

We would use the [go-ipld-prime marshal function](https://github.com/ipld/go-ipld-prime/blob/master/codec/dagcbor/marshal.go#L36)

Its possible it is a simple drop in replacement

**Comment by ABastionOfSanity** [comment] 2023-01-30 22:08
Closed by:
https://github.com/cerc-io/laconicd/pull/88

**Closed by ABastionOfSanity** 2023-01-30 22:08 UTC
